# Change these first
owner: vesahc # Your GitHub organization or username, where this repository lives
repo: upptime-pln # The name of this repository

sites:
- name: arewedistributedyet.com
  url: https://arewedistributedyet.com
- name: badbits.dwebops.pub
  url: https://badbits.dwebops.pub
- name: benchmark-js.ipfs.io
  url: https://benchmark-js.ipfs.io
- name: bifrost-gateway.ipfs.io
  url: https://bifrost-gateway.ipfs.io
- name: bifrost-gateway.stage.ipfs.io
  url: https://bifrost-gateway.stage.ipfs.io
- name: blocks.ipfs.io
  url: https://blocks.ipfs.io
- name: buildingweb3.com
  url: https://buildingweb3.com
- name: chain.love
  url: https://chain.love
- name: consensus-factory.io
  url: https://consensus-factory.io
- name: cryptoeconlab.io
  url: https://cryptoeconlab.io
- name: dag.house
  url: https://dag.house
- name: datacapstats.io
  url: https://datacapstats.io
- name: dataprograms.org
  url: https://dataprograms.org
- name: datatogether.org
  url: https://datatogether.org
- name: dev.webui.ipfs.io
  url: https://dev.webui.ipfs.io
- name: discoursegraphs.ai
  url: https://discoursegraphs.ai
- name: discuss.ipfs.tech
  url: https://discuss.ipfs.tech
- name: dist.ipfs.io
  url: https://dist.ipfs.io
- name: dist.ipfs.tech
  url: https://dist.ipfs.tech
- name: dnslink.dev
  url: https://dnslink.dev
- name: dnslink.io
  url: https://dnslink.io
- name: dnslink.org
  url: https://dnslink.org
- name: drand.love
  url: https://drand.love
- name: fil-safts.com
  url: https://fil-safts.com
- name: fil.space
  url: https://fil.space
- name: filecoin-explorer.com
  url: https://filecoin-explorer.com
- name: filecoin-tracker.com
  url: https://filecoin-tracker.com
- name: filecoin.io
  url: https://filecoin.io
- name: filecointldr.io
  url: https://filecointldr.io
- name: filecoinunleashed.io
  url: https://filecoinunleashed.io
- name: filplus.storage
  url: https://filplus.storage
- name: filpoll.io
  url: https://filpoll.io
- name: flipchart.peerpad.net
  url: https://flipchart.peerpad.net
- name: fundingthecommons.io
  url: https://fundingthecommons.io
- name: igis.io
  url: https://igis.io
- name: impactevaluator.io
  url: https://impactevaluator.io
- name: ipc.space
  url: https://ipc.space
- name: ipfs-project.org
  url: https://ipfs-project.org
- name: ipfs-thing.events
  url: https://ipfs-thing.events
- name: ipfs.cat
  url: https://ipfs.cat
- name: ipfs.network
  url: https://ipfs.network
- name: ipfs.tech
  url: https://ipfs.tech
- name: ipfscluster.io
  url: https://ipfscluster.io
- name: ipfsevents.io
  url: https://ipfsevents.io
- name: ipld.io
  url: https://ipld.io
- name: libp2p.io
  url: https://libp2p.io
- name: lilium.sh
  url: https://lilium.sh
- name: microgen.site
  url: https://microgen.site
- name: mosaia.io
  url: https://mosaia.io
- name: multiformats.io
  url: https://multiformats.io
- name: networkgoods.io
  url: https://networkgoods.io
- name: nftschool.dev
  url: https://nftschool.dev
- name: nftstorage.link
  url: https://nftstorage.link
- name: openpanda.io
  url: https://openpanda.io
- name: peerpad.net
  url: https://peerpad.net
- name: pl-launchpad.io
  url: https://pl-launchpad.io
- name: project-repos.ipfs.io
  url: https://project-repos.ipfs.io
- name: proofs.filecoin.io
  url: https://proofs.filecoin.io
- name: proto.school
  url: https://proto.school
- name: protocol.ai
  url: https://protocol.ai
- name: randomplanetfacts.xyz
  url: https://randomplanetfacts.xyz
- name: recursive.ipfs.io
  url: https://recursive.ipfs.io
- name: refs.ipfs.io
  url: https://refs.ipfs.io
- name: researchroadmaps.ai
  url: https://researchroadmaps.ai
- name: retrieval.market
  url: https://retrieval.market
- name: saft-project.com
  url: https://saft-project.com
- name: saft-project.org
  url: https://saft-project.org
- name: saftproject.com
  url: https://saftproject.com
- name: saturn.tech
  url: https://saturn.tech
- name: sbs.tech
  url: https://sbs.tech
- name: share.ipfs.io
  url: https://share.ipfs.io
- name: shop.filecoin.io
  url: https://shop.filecoin.io
- name: shop.ipfs.io
  url: https://shop.ipfs.io
- name: shop.protocol.ai
  url: https://shop.protocol.ai
- name: singularity.storage
  url: https://singularity.storage
- name: slate.host
  url: https://slate.host
- name: starmap.site
  url: https://starmap.site
- name: trusted-setup-snapdeals.filecoin.io
  url: https://trusted-setup-snapdeals.filecoin.io
- name: trusted-setup.filecoin.io
  url: https://trusted-setup.filecoin.io
- name: webui.ipfs.io
  url: https://webui.ipfs.io
- name: workshop.cluster.ipfs.io
  url: https://workshop.cluster.ipfs.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.outercore.ai
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "PL site uptime monitor and status page."
  introMessage: This is a work in progress PL status page which uses **real-time** data from our [GitHub repository](https://github.com/vesahc/upptime-pln).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
