owner: vesahc
repo: upptime-pln
sites: []
status-website:
  cname: upptime.outercore.ai
  introMessage: This is a work in progress PL status page which uses **real-time**
    data from our [GitHub repository](https://github.com/vesahc/upptime-pln).
  introTitle: PL site uptime monitor and status page.
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
  - href: https://filecoinproject.slack.com/archives/C05NN527TS7
    title: Slack
  scripts:
  - data-domain: upptime.outercore.ai
    defer: true
    src: https://plausible.io/js/script.outbound-links.js
  theme: night
