owner: protocol
repo: upptime-pln
sites:
- name: www.atlas.storage
  url: https://www.atlas.storage
- name: www.buildingweb3.com
  url: https://www.buildingweb3.com
- name: www.cod.cloud
  url: https://www.cod.cloud
- name: www.cryptoeconlab.io
  url: https://www.cryptoeconlab.io
- name: www.drand.love
  url: https://www.drand.love
- name: www.fil.space
  url: https://www.fil.space
- name: www.filecoin-goldenretriever.io
  url: https://www.filecoin-goldenretriever.io
- name: www.filecoin.io
  url: https://www.filecoin.io
- name: www.filecoingreen.io
  url: https://www.filecoingreen.io
- name: www.filstation.app
  url: https://www.filstation.app
- name: www.ipc.space
  url: https://www.ipc.space
- name: www.ipfs.io
  url: https://www.ipfs.io
- name: www.ipfs.network
  url: https://www.ipfs.network
- name: www.ipfs.tech
  url: https://www.ipfs.tech
- name: www.ipfspinningsummit.com
  url: https://www.ipfspinningsummit.com
- name: www.lilium.sh
  url: https://www.lilium.sh
- name: www.microgen.site
  url: https://www.microgen.site
- name: www.mosaia.io
  url: https://www.mosaia.io
- name: www.multiformats.io
  url: https://www.multiformats.io
- name: www.nftschool.dev
  url: https://www.nftschool.dev
- name: www.pl-launchpad.io
  url: https://www.pl-launchpad.io
- name: www.plnetwork.io
  url: https://www.plnetwork.io
- name: www.protocol.ai
  url: https://www.protocol.ai
- name: www.saft-project.com
  url: https://www.saft-project.com
- name: www.saft-project.org
  url: https://www.saft-project.org
- name: www.saftproject.com
  url: https://www.saftproject.com
- name: www.singularity.storage
  url: https://www.singularity.storage
status-website:
  cname: upptime.outercore.ai
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: PL site uptime monitor and status page.
  introMessage: This is a work in progress PL status page which uses **real-time**
    data from our [GitHub repository](https://github.com/$OWNER/$REPO).
  navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/$OWNER/$REPO
  - title: Slack
    href: https://filecoinproject.slack.com/archives/C05NN527TS7
  scripts:
  - src: https://plausible.io/js/script.outbound-links.js
    defer: true
    data-domain: upptime.outercore.ai
  theme: night
