# Change these first
owner: vesahc # Your GitHub organization or username, where this repository lives
repo: upptime-pln # The name of this repository

sites:
  - name: Protocol Labs
    url: https://protocol.ai
  - name: Filecoin
    url: https://filecoin.io
  - name: IPFS
    url: https://ipfs.tech
  - name: libp2p
    url: https://libp2p.io
  - name: ipld
    url: https://ipld.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.outercore.ai
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "PLN site uptime monitor and status page."
  introMessage: This is a work in progress status page which uses **real-time** data from our [GitHub repository](https://github.com/vesahc/upptime-pln).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
